### ISSUE TITLE
No popup for ANY image I mouseover 

### ISSUE THREAD

**Issue by darkred** [tophf/mpiv#17] opened 2020-03-06 16:09 UTC
The commit: [handle autoscaled SVG + code cosmetics](https://github.com/tophf/mpiv/commit/3e1ade87cd2c1450024fb099b2f5a81e9f34f052)
(which was the 4th after the release of v1.1.3),
has caused me the following: 

from that point, there's no popup with the full image for ANY image I mouseover anymore,
the image zoom becomes displayed as `NaN%` at some point, 
but the accompanying text is displayed ok (but only that) on the upper part of the page,
and pressing `t` (open in new tab) or `d` (download image) both still work ok.

Note: the version before that commit, i.e. https://github.com/tophf/mpiv/commit/174366ed6cc328564e3df7487f07a7562c02c62b
works fine.

STR 
in a fresh Chrome profile with only Tampermonkey beta/Violentmonkey and the script of https://github.com/tophf/mpiv/commit/3e1ade87cd2c1450024fb099b2f5a81e9f34f052 
- import my various rules (see below)
- go to e.g. https://www.instagram.com/instagram/
- hover any image. Notice the following:
  - the cursor spins forever as I mouseover any video thumbnail
  - there's no popup (with the full image) for ANY image I mouseover,
  - the first time I mouseover any image, the accompanying text of the relevant post is displayed on top of the page ok (but there's no zoom info, image dimensions or MP). 
If I mouseover again, then the zoom level is displayed as ``NaN%` e.g.
![Screenshot (1538)](https://user-images.githubusercontent.com/723651/76099637-15b35080-5fd4-11ea-9396-9e3d7eeb965f.jpg)
  - pressing `t` (open in new tab) or `d` (download image) both still work ok.

The rules that I import, are too many to post them here, so, I attach them as text file: [my rules.txt](https://github.com/tophf/mpiv/files/4299205/my.rules.txt)

**Comment by tophf** [comment] 2020-03-06 16:14
The bug is caused by "Start preloading immediately" option.
Until I fix it, simply disable the option.

**Comment by tophf** [comment] 2020-03-06 16:21
Fixed in 3e1ade87.

**Closed by tophf** 2020-03-06 16:21 UTC
Labels: bug

**Comment by darkred** [comment] 2020-03-06 16:31
Thanks a lot for the quick fix!

**Comment by tophf** [comment] 2020-03-06 16:32
Thank *you* for testing the "nightlies".

**Comment by darkred** [comment] 2020-03-06 20:45
I have noticed another thing, in all recent versions after 1.0.18 (haven't narrowed it down to a specific commit): **If I hover on a base64 encoded image after having imported my rules, the page hangs.**

STR
in a fresh Chrome profile with only Tampermonkey beta/Violentmonkey and the script with version newer than 1.0.18, e.g. 1.1.0 .
- go to e.g. https://www.base64-image.de/
- drag'n'drop any image
- after the conversion completes click the <kbd></> show code</kbd> button, and mouseover the thumbnail in the overlay that appears: notice that the full image is diplayed ok
- now import [my rules](https://github.com/tophf/mpiv/files/4299205/my.rules.txt) from above and hover the thumbnail: notice that the browser now hangs.
*Disabling the "Start preloading immediately" option makes no difference.*

**Comment by tophf** [comment] 2020-03-07 04:37
Can't reproduce.

**Comment by tophf** [comment] 2020-03-07 04:40
Ah, with a really big image I can.

**Comment by tophf** [comment] 2020-03-07 05:13
Fixed now in MPIV.

The problem was exacerbated by the following rule:
```json
{
  "r": "(.*\\.uvnimg\\.com/.*/)\\?url=(.*)",
  "s": "$2"
}
```

It should be `"(\\.uvnimg\\.com/.*?/)\\?url=(.*)"` or `"(^.*?\\.uvnimg\\.com/.*?/)\\?url=(.*)"`

You're using an unnecessary `.*` in many of your rules, for example: `.*\\.(jpe?|pn)g.*` should be `\\.(jpe?|pn)g` because you're not using those parts covered by `.*` anywhere. The "greedy" `.*` is a known cause for *catastrophic backtracking* so it may take minutes to resolve. If you absolutely have to use it, prefer its non-greedy version `.*?` or find about other ways to safeguard against catastrophic backtracking like positive/negative lookahead.

**Comment by darkred** [comment] 2020-03-07 14:31
Thank you very much for the fix and for the detailed explanation!
I will remove all unecessary `.*` from my rules right away.
