### ISSUE TITLE
Two issues occur with Tampermonkey (ok with Violentmonkey)

### ISSUE THREAD

**Issue by darkred** [tophf/mpiv#3] opened 2020-02-03 17:59 UTC
Using the latest script version with Tampermonkey 4.10.6109 beta in Chrome 79 and Firefox 72 (fresh profiles) in win10. _Both issues don't occur with Violentmonkey._

1. The `d` shortcut to download (pressed while popup is visible) doesn't work. 

2. 
    - In Instagram profiles, the full size only appears for the first 12 pics.  As you scroll further down and mouseover, the cursor just spins endlessly. There's no entry in Console.
e.g. https://www.instagram.com/instagram/
    - In Facebook profile photo pages, no full size images are displayed at all,
e.g. https://www.facebook.com/pg/instagram/photos/
The cursor only spins endlessly as you mouseover. There's no entry in Console.

P.S. Thank you for your awesome work maintaining this super useful script!

**Comment by tophf** [comment] 2020-02-03 18:48
Fixed in the new version via 4aeac35e.

**Closed by tophf** 2020-02-03 18:48 UTC

**Comment by darkred** [comment] 2020-02-03 20:15
Thank you very much for the quick response!

**Comment by darkred** [comment] 2020-03-27 17:00
I've just noticed two more issues that occur only on Tampermonkey (ok in Violentmonkey):
In some pages:
1. the MPIV settings don't appear unless you change the script settings in TM settins from `default` to `document-start`
2. downloading the image in the popup fails

---

STR (for both issues)

(in a fresh Chrome 80.0.3987.149 profile, with TM beta 4.10.6112 and the latest `master` of the script)
- go to e.g. https://www.imdb.com/title/tt8946378/
- try to open MPIV settings panel, it won't open.
*(but if you you change the script `Run at` setting in TM from `default` to `document-start` and reload page, then it will open ok)*
- now in MPIV settings, click "Install rule from repository..." and install the 'IMDb' custom rule
- now mouseover on any thumbnail on the above imdb URL, and press "d":
notice that the image in the popup is not downloaded:
noticed that there's a "Could not download" appended in the title in the black bar.


As I said, everything works fine in Violentmonkey.

**Comment by tophf** [comment] 2020-03-27 19:18
`1` was caused by a bug (or an inherent deficiency) in Tampermonkey: it ignored GM_registerMenuCommand from the main document (it takes longer to load) if an iframe called it first. Fixed.

`2` requires you to whitelist this weird extension in TM's settings. The error message will be shown now. The imdb rule seems to work without `_` in the extension so you can fix it in the rules repo.

**Comment by darkred** [comment] 2020-03-27 19:45
Thanks a lot!
